### ISSUE TITLE
[master-scroll-book] Varbit 5685 does not exist

### ISSUE THREAD

**Issue by YvesW** [Hydrox6/external-plugins#120]
This issue is for the external plugin: master-scroll-book
Plugin version: f46cd0b2728d44aabe2a38240d44edc979f96644

```2024-07-24 20:52:49 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2024-07-24 20:52:49 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.IndexOutOfBoundsException: Varbit 5685 does not exist
	at client.getVarbitValue(client.java:23549)
	at client.getVarbitValue(client.java:9463)
	at io.hydrox.masterscrollbook.MasterScrollBookPlugin.update(MasterScrollBookPlugin.java:155)
	at io.hydrox.masterscrollbook.MasterScrollBookPlugin.onVarbitChanged(MasterScrollBookPlugin.java:111)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:202)
	at client.nf(client.java:5138)
	at client.fs(client.java:28644)
	at client.lu(client.java:3285)
	at client.bw(client.java:1215)
	at bs.nd(bs.java:388)
	at bs.yl(bs.java)
	at bs.run(bs.java:34115)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I've not seen this in my logs before, so Varbit 5685 probably got removed with today's game update.

**Comment by Enriath** [comment]
Ah, that really sucks. Not really sure if there's a reasonable fix for this aside from re-writing the entire plugin, which honestly I'm not particularly keen on doing.

**Comment by YvesW** [comment]
If you're lucky, they just changed the varbit id. In that case, you could yoink it from script 1939 once Polar has updated the cs2 scripts, but we'll see what happened with that script.

**Comment by null-zero** [comment]
From my 2 minutes of testing, they didn't change anything other than the varbit id. Varbit inspector shows the new varbit id as 10966. I submitted #121 as a fix.

**Comment by YvesW** [comment]
Fixed in https://github.com/Enriath/external-plugins/commit/abb005e0a47f5c23cfc172c2e3750881c8135431
